### ISSUE TITLE
usewayland follow GLFW_BUILD_WAYLAND instead of _GLFW_WAYLAND

### ISSUE THREAD

**Issue by duarm** [Swat-SomeBug/glfw#9]
After https://github.com/glfw/glfw/commit/56a4cb0a3a2c7a44a2fd8ab3335adf915e19d30c , glfw can now use the GLFW_BUILD_X11 and GLFW_BUILD_WAYLAND defines to include x11/wayland support, both backends can now coexist and be dinamically selected when opening a window. We should do that instead of an if-else compiling only one backend

https://github.com/glfw/glfw/blob/46cebb5081820418f2a20f3e90b07f9b1bd44b42/src/CMakeLists.txt#L51
```
if (GLFW_BUILD_WAYLAND)
    target_compile_definitions(glfw PRIVATE _GLFW_WAYLAND)
    target_sources(glfw PRIVATE wl_platform.h xkb_unicode.h wl_init.c
                                wl_monitor.c wl_window.c xkb_unicode.c)
endif()
```

**Comment by duarm** [comment]
With the release of 3.8, both are now included by default

**Comment by Swat-SomeBug** [comment]
Hi,

**Comment by Swat-SomeBug** [comment]
Hi,
I was just looking into this and so far I don't see a difference.
Looking at the `CMakeLists.txt`, I see that `_GLFW_X11` and `_GLFW_WAYLAND` are exclusive to each other and any libraries linked at compile time are therefore mutually exclusive.
I'm currently looking at tag `3.3.8`.

**Comment by Swat-SomeBug** [comment]
Is this maybe in the `3.4` release? I see several changes related to Wayland that made it to `3.4`

**Comment by duarm** [comment]
I was referring to this commit, which made into 3.4 release, https://github.com/glfw/glfw/commit/2590d4cdd460b6d4a4bbc17328f283f447f1c3e9

just noticed I typed 3.8, my mistake

**Comment by duarm** [comment]
I'll close this in favor of https://github.com/build2-packaging/glfw/issues/12
